# 向量

In [1]:
import numpy as np

In [2]:
x = np.array([1,2])


In [3]:
print(x)

[1 2]


In [4]:
x1 = np.array([1,2])
x2 = np.array([3,4])
print(x1 + x2)
print(type(x1))

[4 6]
<class 'numpy.ndarray'>


In [5]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [6]:
print(np.arange(5,10))

[5 6 7 8 9]


In [7]:
a = np.array([1,1])
b = a # 将a对应数据的地址赋值给b，类似于C语言中的复制指针
print('a = ' + str(a))
print('b = ' + str(b))
b[0] = 100
print('b = ' + str(b))
print('a = ' + str(a))

a = [1 1]
b = [1 1]
b = [100   1]
a = [100   1]


In [8]:
a = np.array([1,1])
b = a.copy() # 将a对应数据复制一份赋予b
print('a = ' + str(a))
print('b = ' + str(b))
b[0] = 100
print('b = ' + str(b))
print('a = ' + str(a))

a = [1 1]
b = [1 1]
b = [100   1]
a = [1 1]


# 矩阵

In [15]:
import numpy as np


In [20]:
x = np.array([[1,2,3],[4,5,6]])
print(x)
x.shape

[[1 2 3]
 [4 5 6]]


(2, 3)